In [4]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")

import numpy as np
array1 = np.array(range(30))

print(array1)

array2 = array1.reshape(5,6)

print(array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [43]:
#2.呈上題的array，找出被6除餘1的數的索引

array3 = np.where(array2%6 == 1)

print(array3)

array4 = np.transpose(np.ravel(array3).reshape(2,-1))

print(array4)

(array([0, 1, 2, 3, 4], dtype=int64), array([1, 1, 1, 1, 1], dtype=int64))
[[0 1]
 [1 1]
 [2 1]
 [3 1]
 [4 1]]
