In [17]:
#載入Numpy模組，並印出版本號

import numpy as np

print(np.__version__)

'1.19.2'

In [32]:
#list中括號、內容可修改，tuble小括號、內容不可修改、速度較快、資料較安全
#用函式array宣告list a 及 tuble b，並印出各自的內容與類別
#函式種類眾多 array(陣列或元組)/range(起始,終止,間隔)/arange(起始,終止,間隔)

a=np.array([1,2,3])
b=np.array((1,2,3))

print(a,type(a),b,type(b))

[1 2 3] <class 'numpy.ndarray'> [1 2 3] <class 'numpy.ndarray'>


In [34]:
#特別指定型別為浮點數
c=np.arange(1.0, 3.0, 0.5, dtype='float64')

print(c)

#間隔為非整數時不一定會包含結束值，可使用linspace

[1.  1.5 2.  2.5]


In [71]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
d=np.arange(0,21,1)
print(d)

#2.呈上題，將以上數列取出偶數。
e=list(np.arange(0))

for item in d:

    if item%2==0:
        e.append(item)

print(e)

#3.呈1題，將數列取出3的倍數。
f=list(np.arange(0))

for item in d:
    
    if item%3==0:
        f.append(item)
    
print(f)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[0, 3, 6, 9, 12, 15, 18]
